version: "3"

services:
  static-server:
    build: .
    restart: always
    expose:
      - "80"
    volumes:
      - "./files/:/files/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static_webserver.rule=Host(`static.knox.moe`)"
      - "traefik.http.routers.static_webserver.entrypoints=websecure"
      - "traefik.http.routers.static_webserver.tls.certresolver=leresolver"
      - "traefik.docker.network=web_traefik"

networks:
  default:
    external: true
    name: web_traefik

